### ISSUE TITLE
Envelope flattening

### ISSUE THREAD

**Issue by Bird-Bird** [GoranKovac/ReaScripts#10]
Envelope flattening still seems to be present, this time it seems to be happening all the time without any trimming.

![FBmmiTu43d](https://user-images.githubusercontent.com/55462109/72092378-3a1be500-3323-11ea-9840-1646ac2cfbb2.gif)

Edit: I can't seem to recreate it reliably, investigating.

**Comment by GoranKovac** [comment]
cannot reproduce

**Comment by Bird-Bird** [comment]
Could not reproduce again, think I ran an old version by accident.
