### ISSUE TITLE
Silent stops - Area51

### ISSUE THREAD

**Issue by GoranKovac** [GoranKovac/ReaScripts#12]
Silent stops happen in some scenarios when Areas modifier keys (hard coded CTRL+ SHIFT & CTRL+ SHIFT + ALT at the moment) are released while some operation is active on the AREAS.

While the latest fixed reduced them there are still some scenarios when they happen. Fix added additional flag checking if Area is being created so releasing any of modifiers will still intercept mouse and continue to create area until the mouse is released (similar to default behavior Reapers modifiers).

For any new silent stops please add steps to reproduce and GIF since it does not show any errors when it happens.

**Comment by Bird-Bird** [comment]
I believe the `debug = true` flag is causing the silent stops in **Area_51_Refactor** . Commenting it out displays errors as expected when a crash occurs. 
I believe it is because the crash function in **Area_51_Refactor** calls `debug.traceback()` which clashes with the flags name.

**Comment by GoranKovac** [comment]
Renamed it to mouse_debug
