### ISSUE TITLE
"Track > Left drag" mouse modifier context triggers after clicking on TCP when an area is drawn - Area51

### ISSUE THREAD

**Issue by Bird-Bird** [GoranKovac/ReaScripts#18]
![EvTcDeIZJP](https://user-images.githubusercontent.com/55462109/72206708-10d59300-34a2-11ea-99af-73aacc2ef7cd.gif)

**Comment by GoranKovac** [comment]
Cannot reproduce this one, not even sure what I'm seeing ? The mouse click stays down after area is drawn?

**Comment by Bird-Bird** [comment]
Might be a bit hard to see with the gif framerate, here is a video instead: https://streamable.com/8lku2

It left dragged from point A to point B when I clicked on the TCP panel. 
![image](https://user-images.githubusercontent.com/55462109/72206906-43808b00-34a4-11ea-9c9f-63a1f80dab84.png)
