### ISSUE TITLE
Crash when moving items across tracks with overlapping items in the area 

### ISSUE THREAD

**Issue by Bird-Bird** [GoranKovac/ReaScripts#20]
![5j1fSYZs9e](https://user-images.githubusercontent.com/55462109/72218035-454f5a80-3547-11ea-96b1-2645d0853f2b.gif)
Recalculating the selection info before the move operation seems to fix this issue, however I can't figure out why it is happening in the first place except that it passes an item buffer that has invalid MediaItem* to **copy_area_items_into_buffer()**.

**Comment by GoranKovac** [comment]
Strange it only happens if you move selection down, if you move it up its fine....

**Comment by GoranKovac** [comment]
It does not happen in your original Refactor, but there you have other bug that its not deleting items if you move around selection up and down it just copies them. Will take a lot at original buffer code

**Comment by GoranKovac** [comment]
Do not understand why this works when you drag selection UP but not down...

**Comment by Bird-Bird** [comment]
Cannot figure out what causes it either, It is a really weird bug, since it crashes while moving selection down but not up maybe it is related to order of operations somewhere?

**Comment by GoranKovac** [comment]
This is the buffer problem. 
When we go down target which happens to be also source gets deleted so no items go in buffer.
But when going up because of iteration which goes from 1-x it does it can "skip" one track.

if you change this in AreaDo then it will work for down but up will get broken:

"for i = #tbl.sel_info, 1, -1 do"

Will fix this. buffer needs to be filled with all items before we do any operation expecially delete

**Comment by Bird-Bird** [comment]
I have reimplemented it (almost), there is just one detail left, is it possible to know what track we are coming from in **AreaDo()**? I can't figure out if this information is passed anywhere, ideally AreaDo() would be aware of this as it does operations on both the source and target areas.

**Comment by GoranKovac** [comment]
You got it sorted?

When AreaDo(tbl) is called the  table is passed to it, function then just "extracts" that table and does operation we set to it.
If you want to pass other tracks to it or anything then it should be modified to:
AreaDo(tbl,DATA):
Then additional data can be passed to the AreaDo, if you send track for example then in the function:
if xxx = DATA then yyy end

Do not know what you are doing so I cannot help much if I do not see the code

**Comment by Bird-Bird** [comment]
Made a pr https://github.com/GoranKovac/ReaScripts/pull/22

The issue was that while dragging an area the selection info contains the items in the area where you started dragging from, but has no idea what track it is coming from. Not sure if I missed anything but the zone function was only running while dragged, not when clicked. So I had to get the get the track from the item data instead. (That is what the delete function was doing as well)
