### ISSUE TITLE
Unable to move areas with selections that take up exactly one grid unit - Area51

### ISSUE THREAD

**Issue by Bird-Bird** [GoranKovac/ReaScripts#23]
![JbvyUrAJEK](https://user-images.githubusercontent.com/55462109/72255694-72b80900-3618-11ea-8ac5-5495d1c77120.gif)
This is because the zones look at these areas to determine where to trim:
![image](https://user-images.githubusercontent.com/55462109/72255789-b6127780-3618-11ea-813b-7088c451dd83.png)

Ideally it would look at **pixel/screen coordinates** rather than relative to the length of the grid at these areas to determine it, so it would behave consistently independent from the users zoom/grid/selection settings. Like the following image:
![image](https://user-images.githubusercontent.com/55462109/72256022-3e911800-3619-11ea-826c-99f72b59007d.png)

**Comment by GoranKovac** [comment]
Oh yeah, because I've hard coded the range  to be 14 pixels, it needs to be zoom dependent.

Class script :

function Element:zoneIN(x, y)
  local range2 = 14

**Comment by GoranKovac** [comment]
I do not know whats happening I cannot sync my VSCODE with latest dev branch ?? Cant pull

**Comment by Bird-Bird** [comment]
Will check if it is calculating in pixels. Because this is way bigger than 14 pixels but still lets me trim it.
![dQxWCdoDgV](https://user-images.githubusercontent.com/55462109/72258437-258b6580-361f-11ea-920e-e0f8eaf5ea51.gif)


The correct behaviour would be calculating in pixels, that way it behaves the same way regardless of zoom level, like media items in REAPER do:
![kmNwDG8RmY](https://user-images.githubusercontent.com/55462109/72258773-ef021a80-361f-11ea-9c88-5b48afbd372e.gif)
