### ISSUE TITLE
Items in selection move when on last track - Area51

### ISSUE THREAD

**Issue by GoranKovac** [GoranKovac/ReaScripts#24]
Need to fix this.

Dragging selection while selection it touching last project track, items in selection move also

![](https://i.imgur.com/kBs4FOH.gif)

This bug is in the ZONE function.

I've fixed moving up but did not move down

**Comment by GoranKovac** [comment]
Edit: it seems the issue is the new commit in the new paste function since this bug is not present in Refactor branch (I thought I did not fixed this bug)

**Comment by Bird-Bird** [comment]
Should it create new tracks?

**Comment by GoranKovac** [comment]
I can enable that, but I had some horrible time with envelopes in that case. Will jump into this one.

What seems to be the issue is track offset does not move but items get shifted from one track to another

**Comment by Bird-Bird** [comment]
I think it is better to have it stay disabled. Creating new tracks would have to be implemented while dragging to not be confusing. Like REAPER does for media items, otherwise what you see would not match what happens.
![PIPajc3se6](https://user-images.githubusercontent.com/55462109/72260505-0e9b4200-3624-11ea-9427-e7c5048f3a4c.gif)

**Comment by GoranKovac** [comment]
Yeah that was one of the issues I had...  that would be very complicated

**Comment by Bird-Bird** [comment]
I have found more bugs while testing moving with tracks hidden in the track manager:
![QyfZmC8QLb](https://user-images.githubusercontent.com/55462109/72262498-1bba3000-3628-11ea-9430-3df01ad388cd.gif)

**Comment by GoranKovac** [comment]
Will look into it. Working on offset_track function

**Comment by GoranKovac** [comment]
We will need new function for moving envelopes to new tracks now, since refactoring offset function now allows moving anything anywhere, just like standard copy paste.

Its almost finished, but still have some quirks here and there,, and one bug with envelopes

Now is much easier to offset tracks, and draw ghosts. Instead of writing function manually, just calling ghost function will draw them.

**Comment by GoranKovac** [comment]
All this problems are because I'm offsetting tracks on the fly in the zone function. And that is bad but I wrote it that way. It needs to be like copy mode, that one is most accurate. It works with its own "track buffer" which offsets tracks there.

Same implementation needs to be in zone. Thats why I'm refactoring offset function so it will be much easier to work with

**Comment by Bird-Bird** [comment]
Wasn't sure where to write it :P I am taking a bit of a break from Area51. Might take me a while to return (will do eventually), working on some music again, and been playing around with some other scripts when I have some free time.
