### ISSUE TITLE
Typo in tags

### ISSUE THREAD

**Issue by mkruselj** [GoranKovac/ReaScripts#7]
All your scripts have "Discription" instead of "Description", which makes these scripts not show up nicely in ReaPack (with only the script name without author prefix and file type extension). Easy peasy fix :)

Also, Description and ReaScript Name are the same tags. You will want to use About instead of Description!

https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation

**Comment by GoranKovac** [comment]
will do that too
